// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientstream.proto

package com.grpc.clientstream;

public final class clientstreamProto {
  private clientstreamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientstream_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientstream_Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientstream_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientstream_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022clientstream.proto\022\014clientstream\"\026\n\005Va" +
      "lue\022\r\n\005value\030\001 \001(\005\"/\n\006Result\022\013\n\003sum\030\001 \001(" +
      "\005\022\013\n\003cnt\030\002 \001(\005\022\013\n\003avg\030\003 \001(\0012M\n\017AdditionS" +
      "ervice\022:\n\tgetResult\022\023.clientstream.Value" +
      "\032\024.clientstream.Result\"\000(\001B,\n\025com.grpc.c" +
      "lientstreamB\021clientstreamProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_clientstream_Value_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clientstream_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientstream_Value_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_clientstream_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_clientstream_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientstream_Result_descriptor,
        new java.lang.String[] { "Sum", "Cnt", "Avg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
