// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientstream.proto

package com.grpc.clientstream;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clientstream.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum = 1;</code>
   */
  int getSum();

  /**
   * <code>int32 cnt = 2;</code>
   */
  int getCnt();

  /**
   * <code>double avg = 3;</code>
   */
  double getAvg();
}
