// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientstream.proto

package com.grpc.clientstream;

public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clientstream.Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   */
  int getValue();
}
