// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: golden.proto

package com.grpc.golden;

public final class GoldenProto {
  private GoldenProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LightModelListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:golden.LightModelList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    java.util.List<com.grpc.golden.GoldenProto.LightModel> 
        getLightmodelList();
    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    com.grpc.golden.GoldenProto.LightModel getLightmodel(int index);
    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    int getLightmodelCount();
    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    java.util.List<? extends com.grpc.golden.GoldenProto.LightModelOrBuilder> 
        getLightmodelOrBuilderList();
    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    com.grpc.golden.GoldenProto.LightModelOrBuilder getLightmodelOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code golden.LightModelList}
   */
  public  static final class LightModelList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:golden.LightModelList)
      LightModelListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LightModelList.newBuilder() to construct.
    private LightModelList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LightModelList() {
      lightmodel_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LightModelList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                lightmodel_ = new java.util.ArrayList<com.grpc.golden.GoldenProto.LightModel>();
                mutable_bitField0_ |= 0x00000001;
              }
              lightmodel_.add(
                  input.readMessage(com.grpc.golden.GoldenProto.LightModel.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          lightmodel_ = java.util.Collections.unmodifiableList(lightmodel_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.golden.GoldenProto.internal_static_golden_LightModelList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.golden.GoldenProto.internal_static_golden_LightModelList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.golden.GoldenProto.LightModelList.class, com.grpc.golden.GoldenProto.LightModelList.Builder.class);
    }

    public static final int LIGHTMODEL_FIELD_NUMBER = 1;
    private java.util.List<com.grpc.golden.GoldenProto.LightModel> lightmodel_;
    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    public java.util.List<com.grpc.golden.GoldenProto.LightModel> getLightmodelList() {
      return lightmodel_;
    }
    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    public java.util.List<? extends com.grpc.golden.GoldenProto.LightModelOrBuilder> 
        getLightmodelOrBuilderList() {
      return lightmodel_;
    }
    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    public int getLightmodelCount() {
      return lightmodel_.size();
    }
    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    public com.grpc.golden.GoldenProto.LightModel getLightmodel(int index) {
      return lightmodel_.get(index);
    }
    /**
     * <code>repeated .golden.LightModel lightmodel = 1;</code>
     */
    public com.grpc.golden.GoldenProto.LightModelOrBuilder getLightmodelOrBuilder(
        int index) {
      return lightmodel_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < lightmodel_.size(); i++) {
        output.writeMessage(1, lightmodel_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < lightmodel_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, lightmodel_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.golden.GoldenProto.LightModelList)) {
        return super.equals(obj);
      }
      com.grpc.golden.GoldenProto.LightModelList other = (com.grpc.golden.GoldenProto.LightModelList) obj;

      if (!getLightmodelList()
          .equals(other.getLightmodelList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLightmodelCount() > 0) {
        hash = (37 * hash) + LIGHTMODEL_FIELD_NUMBER;
        hash = (53 * hash) + getLightmodelList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.golden.GoldenProto.LightModelList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.golden.GoldenProto.LightModelList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code golden.LightModelList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:golden.LightModelList)
        com.grpc.golden.GoldenProto.LightModelListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.golden.GoldenProto.internal_static_golden_LightModelList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.golden.GoldenProto.internal_static_golden_LightModelList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.golden.GoldenProto.LightModelList.class, com.grpc.golden.GoldenProto.LightModelList.Builder.class);
      }

      // Construct using com.grpc.golden.GoldenProto.LightModelList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLightmodelFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (lightmodelBuilder_ == null) {
          lightmodel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          lightmodelBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.golden.GoldenProto.internal_static_golden_LightModelList_descriptor;
      }

      @java.lang.Override
      public com.grpc.golden.GoldenProto.LightModelList getDefaultInstanceForType() {
        return com.grpc.golden.GoldenProto.LightModelList.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.golden.GoldenProto.LightModelList build() {
        com.grpc.golden.GoldenProto.LightModelList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.golden.GoldenProto.LightModelList buildPartial() {
        com.grpc.golden.GoldenProto.LightModelList result = new com.grpc.golden.GoldenProto.LightModelList(this);
        int from_bitField0_ = bitField0_;
        if (lightmodelBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            lightmodel_ = java.util.Collections.unmodifiableList(lightmodel_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.lightmodel_ = lightmodel_;
        } else {
          result.lightmodel_ = lightmodelBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.golden.GoldenProto.LightModelList) {
          return mergeFrom((com.grpc.golden.GoldenProto.LightModelList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.golden.GoldenProto.LightModelList other) {
        if (other == com.grpc.golden.GoldenProto.LightModelList.getDefaultInstance()) return this;
        if (lightmodelBuilder_ == null) {
          if (!other.lightmodel_.isEmpty()) {
            if (lightmodel_.isEmpty()) {
              lightmodel_ = other.lightmodel_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLightmodelIsMutable();
              lightmodel_.addAll(other.lightmodel_);
            }
            onChanged();
          }
        } else {
          if (!other.lightmodel_.isEmpty()) {
            if (lightmodelBuilder_.isEmpty()) {
              lightmodelBuilder_.dispose();
              lightmodelBuilder_ = null;
              lightmodel_ = other.lightmodel_;
              bitField0_ = (bitField0_ & ~0x00000001);
              lightmodelBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLightmodelFieldBuilder() : null;
            } else {
              lightmodelBuilder_.addAllMessages(other.lightmodel_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.golden.GoldenProto.LightModelList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.golden.GoldenProto.LightModelList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.grpc.golden.GoldenProto.LightModel> lightmodel_ =
        java.util.Collections.emptyList();
      private void ensureLightmodelIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          lightmodel_ = new java.util.ArrayList<com.grpc.golden.GoldenProto.LightModel>(lightmodel_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpc.golden.GoldenProto.LightModel, com.grpc.golden.GoldenProto.LightModel.Builder, com.grpc.golden.GoldenProto.LightModelOrBuilder> lightmodelBuilder_;

      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public java.util.List<com.grpc.golden.GoldenProto.LightModel> getLightmodelList() {
        if (lightmodelBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lightmodel_);
        } else {
          return lightmodelBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public int getLightmodelCount() {
        if (lightmodelBuilder_ == null) {
          return lightmodel_.size();
        } else {
          return lightmodelBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public com.grpc.golden.GoldenProto.LightModel getLightmodel(int index) {
        if (lightmodelBuilder_ == null) {
          return lightmodel_.get(index);
        } else {
          return lightmodelBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public Builder setLightmodel(
          int index, com.grpc.golden.GoldenProto.LightModel value) {
        if (lightmodelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLightmodelIsMutable();
          lightmodel_.set(index, value);
          onChanged();
        } else {
          lightmodelBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public Builder setLightmodel(
          int index, com.grpc.golden.GoldenProto.LightModel.Builder builderForValue) {
        if (lightmodelBuilder_ == null) {
          ensureLightmodelIsMutable();
          lightmodel_.set(index, builderForValue.build());
          onChanged();
        } else {
          lightmodelBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public Builder addLightmodel(com.grpc.golden.GoldenProto.LightModel value) {
        if (lightmodelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLightmodelIsMutable();
          lightmodel_.add(value);
          onChanged();
        } else {
          lightmodelBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public Builder addLightmodel(
          int index, com.grpc.golden.GoldenProto.LightModel value) {
        if (lightmodelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLightmodelIsMutable();
          lightmodel_.add(index, value);
          onChanged();
        } else {
          lightmodelBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public Builder addLightmodel(
          com.grpc.golden.GoldenProto.LightModel.Builder builderForValue) {
        if (lightmodelBuilder_ == null) {
          ensureLightmodelIsMutable();
          lightmodel_.add(builderForValue.build());
          onChanged();
        } else {
          lightmodelBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public Builder addLightmodel(
          int index, com.grpc.golden.GoldenProto.LightModel.Builder builderForValue) {
        if (lightmodelBuilder_ == null) {
          ensureLightmodelIsMutable();
          lightmodel_.add(index, builderForValue.build());
          onChanged();
        } else {
          lightmodelBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public Builder addAllLightmodel(
          java.lang.Iterable<? extends com.grpc.golden.GoldenProto.LightModel> values) {
        if (lightmodelBuilder_ == null) {
          ensureLightmodelIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, lightmodel_);
          onChanged();
        } else {
          lightmodelBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public Builder clearLightmodel() {
        if (lightmodelBuilder_ == null) {
          lightmodel_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          lightmodelBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public Builder removeLightmodel(int index) {
        if (lightmodelBuilder_ == null) {
          ensureLightmodelIsMutable();
          lightmodel_.remove(index);
          onChanged();
        } else {
          lightmodelBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public com.grpc.golden.GoldenProto.LightModel.Builder getLightmodelBuilder(
          int index) {
        return getLightmodelFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public com.grpc.golden.GoldenProto.LightModelOrBuilder getLightmodelOrBuilder(
          int index) {
        if (lightmodelBuilder_ == null) {
          return lightmodel_.get(index);  } else {
          return lightmodelBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public java.util.List<? extends com.grpc.golden.GoldenProto.LightModelOrBuilder> 
           getLightmodelOrBuilderList() {
        if (lightmodelBuilder_ != null) {
          return lightmodelBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lightmodel_);
        }
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public com.grpc.golden.GoldenProto.LightModel.Builder addLightmodelBuilder() {
        return getLightmodelFieldBuilder().addBuilder(
            com.grpc.golden.GoldenProto.LightModel.getDefaultInstance());
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public com.grpc.golden.GoldenProto.LightModel.Builder addLightmodelBuilder(
          int index) {
        return getLightmodelFieldBuilder().addBuilder(
            index, com.grpc.golden.GoldenProto.LightModel.getDefaultInstance());
      }
      /**
       * <code>repeated .golden.LightModel lightmodel = 1;</code>
       */
      public java.util.List<com.grpc.golden.GoldenProto.LightModel.Builder> 
           getLightmodelBuilderList() {
        return getLightmodelFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.grpc.golden.GoldenProto.LightModel, com.grpc.golden.GoldenProto.LightModel.Builder, com.grpc.golden.GoldenProto.LightModelOrBuilder> 
          getLightmodelFieldBuilder() {
        if (lightmodelBuilder_ == null) {
          lightmodelBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.grpc.golden.GoldenProto.LightModel, com.grpc.golden.GoldenProto.LightModel.Builder, com.grpc.golden.GoldenProto.LightModelOrBuilder>(
                  lightmodel_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          lightmodel_ = null;
        }
        return lightmodelBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:golden.LightModelList)
    }

    // @@protoc_insertion_point(class_scope:golden.LightModelList)
    private static final com.grpc.golden.GoldenProto.LightModelList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.golden.GoldenProto.LightModelList();
    }

    public static com.grpc.golden.GoldenProto.LightModelList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LightModelList>
        PARSER = new com.google.protobuf.AbstractParser<LightModelList>() {
      @java.lang.Override
      public LightModelList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LightModelList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LightModelList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LightModelList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.golden.GoldenProto.LightModelList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:golden.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string startTime = 1;</code>
     */
    java.lang.String getStartTime();
    /**
     * <code>string startTime = 1;</code>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    /**
     * <code>string endTime = 2;</code>
     */
    java.lang.String getEndTime();
    /**
     * <code>string endTime = 2;</code>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();

    /**
     * <code>string real_tag = 3;</code>
     */
    java.lang.String getRealTag();
    /**
     * <code>string real_tag = 3;</code>
     */
    com.google.protobuf.ByteString
        getRealTagBytes();
  }
  /**
   * Protobuf type {@code golden.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:golden.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      startTime_ = "";
      endTime_ = "";
      realTag_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              startTime_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              endTime_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              realTag_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.golden.GoldenProto.internal_static_golden_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.golden.GoldenProto.internal_static_golden_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.golden.GoldenProto.Request.class, com.grpc.golden.GoldenProto.Request.Builder.class);
    }

    public static final int STARTTIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object startTime_;
    /**
     * <code>string startTime = 1;</code>
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      }
    }
    /**
     * <code>string startTime = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDTIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object endTime_;
    /**
     * <code>string endTime = 2;</code>
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      }
    }
    /**
     * <code>string endTime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REAL_TAG_FIELD_NUMBER = 3;
    private volatile java.lang.Object realTag_;
    /**
     * <code>string real_tag = 3;</code>
     */
    public java.lang.String getRealTag() {
      java.lang.Object ref = realTag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realTag_ = s;
        return s;
      }
    }
    /**
     * <code>string real_tag = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRealTagBytes() {
      java.lang.Object ref = realTag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realTag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStartTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, startTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, endTime_);
      }
      if (!getRealTagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, realTag_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStartTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, startTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, endTime_);
      }
      if (!getRealTagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, realTag_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.golden.GoldenProto.Request)) {
        return super.equals(obj);
      }
      com.grpc.golden.GoldenProto.Request other = (com.grpc.golden.GoldenProto.Request) obj;

      if (!getStartTime()
          .equals(other.getStartTime())) return false;
      if (!getEndTime()
          .equals(other.getEndTime())) return false;
      if (!getRealTag()
          .equals(other.getRealTag())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getEndTime().hashCode();
      hash = (37 * hash) + REAL_TAG_FIELD_NUMBER;
      hash = (53 * hash) + getRealTag().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.golden.GoldenProto.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.golden.GoldenProto.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.golden.GoldenProto.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.golden.GoldenProto.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.golden.GoldenProto.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.golden.GoldenProto.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.golden.GoldenProto.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.golden.GoldenProto.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code golden.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:golden.Request)
        com.grpc.golden.GoldenProto.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.golden.GoldenProto.internal_static_golden_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.golden.GoldenProto.internal_static_golden_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.golden.GoldenProto.Request.class, com.grpc.golden.GoldenProto.Request.Builder.class);
      }

      // Construct using com.grpc.golden.GoldenProto.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        startTime_ = "";

        endTime_ = "";

        realTag_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.golden.GoldenProto.internal_static_golden_Request_descriptor;
      }

      @java.lang.Override
      public com.grpc.golden.GoldenProto.Request getDefaultInstanceForType() {
        return com.grpc.golden.GoldenProto.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.golden.GoldenProto.Request build() {
        com.grpc.golden.GoldenProto.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.golden.GoldenProto.Request buildPartial() {
        com.grpc.golden.GoldenProto.Request result = new com.grpc.golden.GoldenProto.Request(this);
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        result.realTag_ = realTag_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.golden.GoldenProto.Request) {
          return mergeFrom((com.grpc.golden.GoldenProto.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.golden.GoldenProto.Request other) {
        if (other == com.grpc.golden.GoldenProto.Request.getDefaultInstance()) return this;
        if (!other.getStartTime().isEmpty()) {
          startTime_ = other.startTime_;
          onChanged();
        }
        if (!other.getEndTime().isEmpty()) {
          endTime_ = other.endTime_;
          onChanged();
        }
        if (!other.getRealTag().isEmpty()) {
          realTag_ = other.realTag_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.golden.GoldenProto.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.golden.GoldenProto.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object startTime_ = "";
      /**
       * <code>string startTime = 1;</code>
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string startTime = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string startTime = 1;</code>
       */
      public Builder setStartTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string startTime = 1;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>string startTime = 1;</code>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endTime_ = "";
      /**
       * <code>string endTime = 2;</code>
       */
      public java.lang.String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string endTime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        java.lang.Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string endTime = 2;</code>
       */
      public Builder setEndTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string endTime = 2;</code>
       */
      public Builder clearEndTime() {
        
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <code>string endTime = 2;</code>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object realTag_ = "";
      /**
       * <code>string real_tag = 3;</code>
       */
      public java.lang.String getRealTag() {
        java.lang.Object ref = realTag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          realTag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string real_tag = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRealTagBytes() {
        java.lang.Object ref = realTag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          realTag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string real_tag = 3;</code>
       */
      public Builder setRealTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        realTag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string real_tag = 3;</code>
       */
      public Builder clearRealTag() {
        
        realTag_ = getDefaultInstance().getRealTag();
        onChanged();
        return this;
      }
      /**
       * <code>string real_tag = 3;</code>
       */
      public Builder setRealTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        realTag_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:golden.Request)
    }

    // @@protoc_insertion_point(class_scope:golden.Request)
    private static final com.grpc.golden.GoldenProto.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.golden.GoldenProto.Request();
    }

    public static com.grpc.golden.GoldenProto.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.golden.GoldenProto.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LightModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:golden.LightModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tagName = 1;</code>
     */
    java.lang.String getTagName();
    /**
     * <code>string tagName = 1;</code>
     */
    com.google.protobuf.ByteString
        getTagNameBytes();

    /**
     * <code>string tagTime = 2;</code>
     */
    java.lang.String getTagTime();
    /**
     * <code>string tagTime = 2;</code>
     */
    com.google.protobuf.ByteString
        getTagTimeBytes();

    /**
     * <code>string tagValue = 3;</code>
     */
    java.lang.String getTagValue();
    /**
     * <code>string tagValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getTagValueBytes();

    /**
     * <code>bool isGood = 4;</code>
     */
    boolean getIsGood();

    /**
     * <code>int32 quality = 5;</code>
     */
    int getQuality();

    /**
     * <code>bool setps = 6;</code>
     */
    boolean getSetps();
  }
  /**
   * Protobuf type {@code golden.LightModel}
   */
  public  static final class LightModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:golden.LightModel)
      LightModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LightModel.newBuilder() to construct.
    private LightModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LightModel() {
      tagName_ = "";
      tagTime_ = "";
      tagValue_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LightModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tagName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tagTime_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              tagValue_ = s;
              break;
            }
            case 32: {

              isGood_ = input.readBool();
              break;
            }
            case 40: {

              quality_ = input.readInt32();
              break;
            }
            case 48: {

              setps_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpc.golden.GoldenProto.internal_static_golden_LightModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpc.golden.GoldenProto.internal_static_golden_LightModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpc.golden.GoldenProto.LightModel.class, com.grpc.golden.GoldenProto.LightModel.Builder.class);
    }

    public static final int TAGNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object tagName_;
    /**
     * <code>string tagName = 1;</code>
     */
    public java.lang.String getTagName() {
      java.lang.Object ref = tagName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tagName_ = s;
        return s;
      }
    }
    /**
     * <code>string tagName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTagNameBytes() {
      java.lang.Object ref = tagName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tagName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGTIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object tagTime_;
    /**
     * <code>string tagTime = 2;</code>
     */
    public java.lang.String getTagTime() {
      java.lang.Object ref = tagTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tagTime_ = s;
        return s;
      }
    }
    /**
     * <code>string tagTime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTagTimeBytes() {
      java.lang.Object ref = tagTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tagTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGVALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object tagValue_;
    /**
     * <code>string tagValue = 3;</code>
     */
    public java.lang.String getTagValue() {
      java.lang.Object ref = tagValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tagValue_ = s;
        return s;
      }
    }
    /**
     * <code>string tagValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTagValueBytes() {
      java.lang.Object ref = tagValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tagValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISGOOD_FIELD_NUMBER = 4;
    private boolean isGood_;
    /**
     * <code>bool isGood = 4;</code>
     */
    public boolean getIsGood() {
      return isGood_;
    }

    public static final int QUALITY_FIELD_NUMBER = 5;
    private int quality_;
    /**
     * <code>int32 quality = 5;</code>
     */
    public int getQuality() {
      return quality_;
    }

    public static final int SETPS_FIELD_NUMBER = 6;
    private boolean setps_;
    /**
     * <code>bool setps = 6;</code>
     */
    public boolean getSetps() {
      return setps_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTagNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tagName_);
      }
      if (!getTagTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tagTime_);
      }
      if (!getTagValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tagValue_);
      }
      if (isGood_ != false) {
        output.writeBool(4, isGood_);
      }
      if (quality_ != 0) {
        output.writeInt32(5, quality_);
      }
      if (setps_ != false) {
        output.writeBool(6, setps_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTagNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tagName_);
      }
      if (!getTagTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tagTime_);
      }
      if (!getTagValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tagValue_);
      }
      if (isGood_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isGood_);
      }
      if (quality_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, quality_);
      }
      if (setps_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, setps_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpc.golden.GoldenProto.LightModel)) {
        return super.equals(obj);
      }
      com.grpc.golden.GoldenProto.LightModel other = (com.grpc.golden.GoldenProto.LightModel) obj;

      if (!getTagName()
          .equals(other.getTagName())) return false;
      if (!getTagTime()
          .equals(other.getTagTime())) return false;
      if (!getTagValue()
          .equals(other.getTagValue())) return false;
      if (getIsGood()
          != other.getIsGood()) return false;
      if (getQuality()
          != other.getQuality()) return false;
      if (getSetps()
          != other.getSetps()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TAGNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTagName().hashCode();
      hash = (37 * hash) + TAGTIME_FIELD_NUMBER;
      hash = (53 * hash) + getTagTime().hashCode();
      hash = (37 * hash) + TAGVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getTagValue().hashCode();
      hash = (37 * hash) + ISGOOD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsGood());
      hash = (37 * hash) + QUALITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuality();
      hash = (37 * hash) + SETPS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSetps());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpc.golden.GoldenProto.LightModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpc.golden.GoldenProto.LightModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpc.golden.GoldenProto.LightModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code golden.LightModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:golden.LightModel)
        com.grpc.golden.GoldenProto.LightModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpc.golden.GoldenProto.internal_static_golden_LightModel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpc.golden.GoldenProto.internal_static_golden_LightModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpc.golden.GoldenProto.LightModel.class, com.grpc.golden.GoldenProto.LightModel.Builder.class);
      }

      // Construct using com.grpc.golden.GoldenProto.LightModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tagName_ = "";

        tagTime_ = "";

        tagValue_ = "";

        isGood_ = false;

        quality_ = 0;

        setps_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpc.golden.GoldenProto.internal_static_golden_LightModel_descriptor;
      }

      @java.lang.Override
      public com.grpc.golden.GoldenProto.LightModel getDefaultInstanceForType() {
        return com.grpc.golden.GoldenProto.LightModel.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpc.golden.GoldenProto.LightModel build() {
        com.grpc.golden.GoldenProto.LightModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpc.golden.GoldenProto.LightModel buildPartial() {
        com.grpc.golden.GoldenProto.LightModel result = new com.grpc.golden.GoldenProto.LightModel(this);
        result.tagName_ = tagName_;
        result.tagTime_ = tagTime_;
        result.tagValue_ = tagValue_;
        result.isGood_ = isGood_;
        result.quality_ = quality_;
        result.setps_ = setps_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpc.golden.GoldenProto.LightModel) {
          return mergeFrom((com.grpc.golden.GoldenProto.LightModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpc.golden.GoldenProto.LightModel other) {
        if (other == com.grpc.golden.GoldenProto.LightModel.getDefaultInstance()) return this;
        if (!other.getTagName().isEmpty()) {
          tagName_ = other.tagName_;
          onChanged();
        }
        if (!other.getTagTime().isEmpty()) {
          tagTime_ = other.tagTime_;
          onChanged();
        }
        if (!other.getTagValue().isEmpty()) {
          tagValue_ = other.tagValue_;
          onChanged();
        }
        if (other.getIsGood() != false) {
          setIsGood(other.getIsGood());
        }
        if (other.getQuality() != 0) {
          setQuality(other.getQuality());
        }
        if (other.getSetps() != false) {
          setSetps(other.getSetps());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.grpc.golden.GoldenProto.LightModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.grpc.golden.GoldenProto.LightModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tagName_ = "";
      /**
       * <code>string tagName = 1;</code>
       */
      public java.lang.String getTagName() {
        java.lang.Object ref = tagName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tagName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tagName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTagNameBytes() {
        java.lang.Object ref = tagName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tagName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tagName = 1;</code>
       */
      public Builder setTagName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tagName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tagName = 1;</code>
       */
      public Builder clearTagName() {
        
        tagName_ = getDefaultInstance().getTagName();
        onChanged();
        return this;
      }
      /**
       * <code>string tagName = 1;</code>
       */
      public Builder setTagNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tagName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tagTime_ = "";
      /**
       * <code>string tagTime = 2;</code>
       */
      public java.lang.String getTagTime() {
        java.lang.Object ref = tagTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tagTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tagTime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTagTimeBytes() {
        java.lang.Object ref = tagTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tagTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tagTime = 2;</code>
       */
      public Builder setTagTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tagTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tagTime = 2;</code>
       */
      public Builder clearTagTime() {
        
        tagTime_ = getDefaultInstance().getTagTime();
        onChanged();
        return this;
      }
      /**
       * <code>string tagTime = 2;</code>
       */
      public Builder setTagTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tagTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tagValue_ = "";
      /**
       * <code>string tagValue = 3;</code>
       */
      public java.lang.String getTagValue() {
        java.lang.Object ref = tagValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tagValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tagValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTagValueBytes() {
        java.lang.Object ref = tagValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tagValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tagValue = 3;</code>
       */
      public Builder setTagValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tagValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tagValue = 3;</code>
       */
      public Builder clearTagValue() {
        
        tagValue_ = getDefaultInstance().getTagValue();
        onChanged();
        return this;
      }
      /**
       * <code>string tagValue = 3;</code>
       */
      public Builder setTagValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tagValue_ = value;
        onChanged();
        return this;
      }

      private boolean isGood_ ;
      /**
       * <code>bool isGood = 4;</code>
       */
      public boolean getIsGood() {
        return isGood_;
      }
      /**
       * <code>bool isGood = 4;</code>
       */
      public Builder setIsGood(boolean value) {
        
        isGood_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isGood = 4;</code>
       */
      public Builder clearIsGood() {
        
        isGood_ = false;
        onChanged();
        return this;
      }

      private int quality_ ;
      /**
       * <code>int32 quality = 5;</code>
       */
      public int getQuality() {
        return quality_;
      }
      /**
       * <code>int32 quality = 5;</code>
       */
      public Builder setQuality(int value) {
        
        quality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quality = 5;</code>
       */
      public Builder clearQuality() {
        
        quality_ = 0;
        onChanged();
        return this;
      }

      private boolean setps_ ;
      /**
       * <code>bool setps = 6;</code>
       */
      public boolean getSetps() {
        return setps_;
      }
      /**
       * <code>bool setps = 6;</code>
       */
      public Builder setSetps(boolean value) {
        
        setps_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool setps = 6;</code>
       */
      public Builder clearSetps() {
        
        setps_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:golden.LightModel)
    }

    // @@protoc_insertion_point(class_scope:golden.LightModel)
    private static final com.grpc.golden.GoldenProto.LightModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpc.golden.GoldenProto.LightModel();
    }

    public static com.grpc.golden.GoldenProto.LightModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LightModel>
        PARSER = new com.google.protobuf.AbstractParser<LightModel>() {
      @java.lang.Override
      public LightModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LightModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LightModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LightModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpc.golden.GoldenProto.LightModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_golden_LightModelList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_golden_LightModelList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_golden_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_golden_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_golden_LightModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_golden_LightModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014golden.proto\022\006golden\"8\n\016LightModelList" +
      "\022&\n\nlightmodel\030\001 \003(\0132\022.golden.LightModel" +
      "\"?\n\007Request\022\021\n\tstartTime\030\001 \001(\t\022\017\n\007endTim" +
      "e\030\002 \001(\t\022\020\n\010real_tag\030\003 \001(\t\"p\n\nLightModel\022" +
      "\017\n\007tagName\030\001 \001(\t\022\017\n\007tagTime\030\002 \001(\t\022\020\n\010tag" +
      "Value\030\003 \001(\t\022\016\n\006isGood\030\004 \001(\010\022\017\n\007quality\030\005" +
      " \001(\005\022\r\n\005setps\030\006 \001(\0102L\n\007ReadRaw\022A\n\022readRa" +
      "wValuesModel\022\017.golden.Request\032\026.golden.L" +
      "ightModelList\"\000(\001B \n\017com.grpc.goldenB\013Go" +
      "ldenProtoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_golden_LightModelList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_golden_LightModelList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_golden_LightModelList_descriptor,
        new java.lang.String[] { "Lightmodel", });
    internal_static_golden_Request_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_golden_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_golden_Request_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "RealTag", });
    internal_static_golden_LightModel_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_golden_LightModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_golden_LightModel_descriptor,
        new java.lang.String[] { "TagName", "TagTime", "TagValue", "IsGood", "Quality", "Setps", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
