// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverstream.proto

package com.grpc.serverstream;

public interface IPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serverstream.IP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string IP = 1;</code>
   */
  java.lang.String getIP();
  /**
   * <code>string IP = 1;</code>
   */
  com.google.protobuf.ByteString
      getIPBytes();
}
