// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverstream.proto

package com.grpc.serverstream;

public interface NameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serverstream.Name)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
