// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serverstream.proto

package com.grpc.serverstream;

public final class ServerStreamProto {
  private ServerStreamProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serverstream_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serverstream_Name_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serverstream_IP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serverstream_IP_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022serverstream.proto\022\014serverstream\"\024\n\004Na" +
      "me\022\014\n\004name\030\001 \001(\t\"\020\n\002IP\022\n\n\002IP\030\001 \001(\t2F\n\013Na" +
      "meService\0227\n\013getIpByName\022\022.serverstream." +
      "Name\032\020.serverstream.IP\"\0000\001B,\n\025com.grpc.s" +
      "erverstreamB\021ServerStreamProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_serverstream_Name_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serverstream_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serverstream_Name_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_serverstream_IP_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_serverstream_IP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serverstream_IP_descriptor,
        new java.lang.String[] { "IP", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
